# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a711f55351ce0a12c66b780441700c36ffe2855bb18dc17c554a88372be354adb869c44a2539ab8c224de1cb037ab91a2984be9067ecead9539723328bd0d4b1

test:
  secret_key_base: c102e66b46bf70deed1c4a4345b29599671ce77bc521cb2a289f3d50019b2451ae9e6f6b9a97ee4afecf07ebe33d4c3b433a89e38cd51620ac8f70b4326e5a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
